
name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10
      
      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn make

      - name: Upload builds for macos
        uses: softprops/action-gh-release@v1
        if: startsWith(matrix.os, 'macos')
        with:
          tag_name: ${{ github.ref }}
          files: out/**/*!(.zip)
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Upload builds to ubuntu
        uses: softprops/action-gh-release@v1
        if: startsWith(matrix.os, 'ubuntu')
        with:
          tag_name: ${{ github.ref }}
          files: out/**/*!(.deb)
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload builds to windows
        uses: softprops/action-gh-release@v1
        if: matrix.os == 'windows-latest'
        with:
          tag_name: ${{ github.ref }}
          files: out/**/*!(.exe)
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}